name: Keep Alive
on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Server
        run: curl -s https://employeetrack-backend.onrender.com/awakeup
